build_job:
  image: python:3.11.8
  script:
    - echo "Building with Python 3.11.8"

test_docker_job:
  image: docker:latest
  script:
    - docker version
    - docker ps
    - docker run python:3.11.8 python
