version: "3.3"
services:

  db:
    image: postgres:15
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=exonys@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=1
    ports:
      - 8080:80
    networks:
      - default

  #  queue:
  #    image: redis
  #    networks:
  #      - default
  #    ports:
  #      - 6379:6379


  backend:
    restart: always
    command: bash -c "uvicorn backend.app.main:app --host 0.0.0.0 --port ${SERVICE_PORT} --reload"
    #    command:  sh /root_app/backend/entry-point.sh
    #image: conspectus_backend
    container_name: pixel_battle_backend
    tty: true
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    #      - SERVICE_PORT:8000
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    networks:
      - default
    volumes:
      - ./backend:/root_app/backend
      - ./common:/root_app/common
      - ./backend/app:/root_app/backend/app
    build:
      context: .
      dockerfile: ./backend/backend.dockerfile
      args:
        INSTALL_DEV: yes


volumes:
  app-db-data:

